[profile.default]
src = 'contract/src'
out = 'contract/out'
test = 'contract/tests'
script = 'contract/script'
libs = ['lib']
solc-version = "0.8.20"


remapping = ["@openzeppelin/=lib/openzeppelin-contracts/"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config