[profile.default]
src = 'src'
out = 'out'
test = 'tests'
script = 'script'
libs = ['lib']
solc-version = "0.8.20"


remapping = ["@openzeppelin/=lib/openzeppelin-contracts/"]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config